# Generated by Django 4.2.11 on 2024-03-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_create_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('id',)},
        ),
    ]
